services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-dev-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=fastkit_user
      - POSTGRES_DB=fastkit_db
volumes:
  db-dev-data: